# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyeccion', '0005_programa_proyecto_recursodocente_recursoestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='informacion_descriptiva_id',
        ),
        migrations.AddField(
            model_name='informaciondescriptiva',
            name='proyecto_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Proyeccion.Proyecto'),
        ),
    ]
